In [1]:
import numpy as np

In [5]:
a_arr = np.array([[1,2,3],
                  [5,6,7]])
b_arr = a_arr[:,1:3]

In [6]:
print(a_arr)
print(b_arr)

[[1 2 3]
 [5 6 7]]
[[2 3]
 [6 7]]


In [8]:
a_arr = np.array([[1,2,3],
                  [5,6,7]])
print('a_arr \n', a_arr)
b_arr = a_arr[:, 1:3]
print('b_arr',b_arr)

print('before changing \n', a_arr[0,1])
b_arr[0,0]=99
print('after changing \n',a_arr[0, 1])


a_arr 
 [[1 2 3]
 [5 6 7]]
b_arr [[2 3]
 [6 7]]
before changing 
 2
after changing 
 99


In [10]:
arr = np.array([[1,2,3],
                [5,6,7],
                [9,10,11]])
# Hai cach truy cap du lieu o cot index=1 cua mang

row_m1 = arr[1,:]
row_m2 = arr[1:2, :]
print(row_m1, row_m1.shape)
print(row_m2,row_m2.shape)

[5 6 7] (3,)
[[5 6 7]] (1, 3)


In [13]:
arr = np.array([[1,2,3],
                [5,6,7],
                [9,10,11]])
# Hai cach truy cap du lieu o cot index=1 cua mang

row_m1 = arr[:, 1]
row_m2 = arr[:, 1:2]
print(row_m1, row_m1.shape)
print(row_m2,row_m2.shape)

[ 2  6 10] (3,)
[[ 2]
 [ 6]
 [10]] (3, 1)


In [12]:
# lay gia tri ()
out1 = arr[[0,1,2], [0,1,0]]
print('out1', out1)
 
out2 = arr[[0,0],[1,1]]
print('out2:\n',out2)

out1 [1 6 9]
out2:
 [2 2]


In [14]:
arr = np.array([[1,2],
                [3,4],
                [5,6]])
print(arr)

# tm cac phan tu lon hon 2
bool_idx = (arr > 2)
print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [15]:
x = np.array([1,2,3,4])
y = np.array([5,6,7,8])

print('data x \n', x)
print('data y \n', y)

# Tong cua 2 mang
print('method 1 \n', x+y)
print('method 2 \n', np.add(x,y))

data x 
 [1 2 3 4]
data y 
 [5 6 7 8]
method 1 
 [ 6  8 10 12]
method 2 
 [ 6  8 10 12]


In [18]:
# phep chia cac tung phan tuong ung x cho y
print('method 1 \n', x/y)
print('method 2 \n', x//y)
print('method 3 \n', np.divide(x, y))

method 1 
 [0.2        0.33333333 0.42857143 0.5       ]
method 2 
 [0 0 0 0]
method 3 
 [0.2        0.33333333 0.42857143 0.5       ]


In [20]:
# can bac 2 tung phan tu trong data
data = np.array([1,2,3,4])
print('data \n',data)
print('sqrt \n',np.sqrt(data))

data 
 [1 2 3 4]
sqrt 
 [1.         1.41421356 1.73205081 2.        ]


In [21]:
v = np.array([1, 2])
w = np.array([2, 3])

#Tinh inner product giua v va w
print('method 1 \n', v.dot(w))
print('method 2 \n', np.dot(v, w))

method 1 
 8
method 2 
 8


In [22]:
X = np.array([[1,2],
              [3,4]])
v = np.array([1,2])

print('matrix X \n',X)
print('vector v \n',v)

# phep nhan giua ma tran va vector
print('method 1: X.dot(v)\n', X.dot(v))
print('method 1: v.dot(X)\n', v.dot(X))

matrix X 
 [[1 2]
 [3 4]]
vector v 
 [1 2]
method 1: X.dot(v)
 [ 5 11]
method 1: v.dot(X)
 [ 7 10]


In [24]:
Y = np.array([[2,3],
              [2,1]])
print('method 1 \n', X.dot(Y))
print('method 1 \n',Y.dot(X))

method 1 
 [[ 6  5]
 [14 13]]
method 1 
 [[11 16]
 [ 5  8]]


In [25]:
X = np.array([[1,2],
              [3,4]])
print(np.sum(X))
# Tong theo cot
print(np.sum(X, axis=0))
print(np.sum(X, axis=1))

10
[4 6]
[3 7]


In [26]:
data = np.array([1,2,3])
print(data.max())
print(data.min())

3
1


In [30]:
# nhan va tru vs 1 so
factor =2
result_multiplication = data*factor
result_minus = data - factor

print(data) 
print(result_multiplication)
print(result_minus)

[1 2 3]
[2 4 6]
[-1  0  1]


In [32]:
X = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
v = np.array([1, 0, 1])

Y = X +v
print(Y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]]


###### Introduction Numpy

In [1]:
import tensorflow as tf
import numpy as np

In [5]:
# create a numpy array
arr_np = np.arange(10)
print(arr_np)
print(arr_np.shape)
print('-------------')

[0 1 2 3 4 5 6 7 8 9]
(10,)
-------------


In [6]:
# convert from numpy array to tensor
arr_tf = tf.convert_to_tensor(arr_np)
print(arr_tf)
print(arr_tf.shape)
print('--------------')

tf.Tensor([0 1 2 3 4 5 6 7 8 9], shape=(10,), dtype=int64)
(10,)
--------------


In [7]:
# convert from tensor to numpy array
arr_np_back = arr_tf.numpy()
print(arr_np_back)
print(arr_np_back.shape)

[0 1 2 3 4 5 6 7 8 9]
(10,)


In [15]:
#Common attributes
import numpy as np

# tao list
l = list(range(1,4))

list1D = [1,2,3]

list2D = [[1,2],[3,4],[5,6]]

list3D = [[[1,6],[2,2],[3,4]],
          [[4,7],[5,3],[6,9]],
          [[7,7],[8,2],[9,3]]]
# tao ndarray
data = np.array(l)
data1 = np.array(list1D)
data2 = np.array(list2D)
data3 = np.array(list3D)

print(data)
print(data1)
print(data2)
print(data3)

[1 2 3]
[1 2 3]
[[1 2]
 [3 4]
 [5 6]]
[[[1 6]
  [2 2]
  [3 4]]

 [[4 7]
  [5 3]
  [6 9]]

 [[7 7]
  [8 2]
  [9 3]]]


In [17]:
#Thay doi gia tri phan tu
import numpy as np

#Create list
l = list(range(1,4))

#tao ndarray
data = np.array(l)
print(data)
data[0] = 8
print(data)

[1 2 3]
[8 2 3]


In [19]:
# tao mot numpy array
# voi phan tu la 0
import numpy as np
# shape: 2 dong , 3 cot
arr = np.zeros((2,3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [21]:
# tao mot numpy array voi
# numpy.ones(shape)
#shape: 2 dong 3 cot
arr = np.ones((2,3))
print(arr)

[[1. 1. 1.]
 [1. 1. 1.]]


In [22]:
arr = np.full((2,3),9)
print(arr)

[[9 9 9]
 [9 9 9]]


In [23]:
#tao array
arr1 = np.arange(5)
print(arr1)

arr2 = np.arange(0,5,2)
print(arr2)

[0 1 2 3 4]
[0 2 4]


In [25]:
# tao arrray voi duong cheo la so 1

arr = np.eye(3)
print(arr)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [27]:
#phan tu co gia tri ngau nhien
arr = np.random.random((2,3))
print(arr)

[[0.28661374 0.47335996 0.26492827]
 [0.14078698 0.61797128 0.27597937]]


In [28]:
arr = np.array(5)
print(arr)

condition = arr < 3
out =np.where(condition, arr, arr*2)

print(condition)
print(out)

5
False
10


In [29]:
arr = np.array([[1,2],[3,4]])
out = arr.flatten()

print(arr)
print(out)

[[1 2]
 [3 4]]
[1 2 3 4]


In [ ]:
# tao list
l =[[1,2,3],
    [4,5,6]]
# Tao ndarray
data = np.array(l)
print('data\n', data)
print('data shape\n', data.shape)

#reshape
data_rs = np.reshape(data,(3,2))
print('data_rs\n', data_rs)
print('data_rs shape\n'. data_rs)

###### Data Processing

In [2]:
import numpy as np
import numpy.core.defchararray as np_f


In [13]:
X = np.genfromtxt('/Users/vothaianh/Downloads/[FreeTutorials.Eu] Udemy - NLP - Natural Language Processing with Python--Hoc RR/1. Introduction/UPDATED_NLP_COURSE/06-Deep-Learning/irisdata.csv',delimiter=',', dtype='str',usecols=[0,1,2,3],skip_header=1)

In [14]:
print(X.shape)

(150, 4)


In [15]:
# lay species va luu vao bien y
y = np.genfromtxt('/Users/vothaianh/Downloads/[FreeTutorials.Eu] Udemy - NLP - Natural Language Processing with Python--Hoc RR/1. Introduction/UPDATED_NLP_COURSE/06-Deep-Learning/irisdata.csv',delimiter=',', dtype='str',usecols=[0,1,2,3],skip_header=1)

In [21]:
# thay chuoi bang so
categories = np.unique(y)
for i in range(categories.size):
    y = np_f.replace(y, categories[i], str(i))

# dua ve kieu float
Y = y.astype('float')
print(y)

[['45616' '256056' '55956' '56']
 ['3565' '256' '55956' '56']
 ['3563' '2556656' '55856' '56']
 ['35616' '25616' '56056' '56']
 ['456' '25616' '55956' '56']
 ['455956' '2565' '563' '256']
 ['35616' '255956' '55956' '156']
 ['456' '255956' '56056' '56']
 ['355956' '1565' '55956' '56']
 ['3565' '25616' '56056' '0']
 ['455956' '2563' '56056' '56']
 ['3564' '255956' '5616' '56']
 ['3564' '256' '55956' '0']
 ['355856' '256' '5616' '0']
 ['4564' '356' '556656' '56']
 ['4563' '355956' '56056' '256']
 ['455956' '2565' '55856' '256']
 ['45616' '256056' '55956' '156']
 ['4563' '2564' '563' '156']
 ['45616' '2564' '56056' '156']
 ['455956' '255956' '563' '56']
 ['45616' '2563' '56056' '256']
 ['35616' '25616' '56' '56']
 ['45616' '255856' '563' '356']
 ['3564' '255956' '565' '56']
 ['456' '256' '5616' '56']
 ['456' '255956' '5616' '256']
 ['4556656' '256056' '56056' '56']
 ['4556656' '255956' '55956' '56']
 ['3563' '2556656' '5616' '56']
 ['3564' '25616' '5616' '56']
 ['455956' '255956' '56056' '